INSERT INTO public.pais (id_pais, pais) VALUES (1, 'Colombia');
INSERT INTO public.pais (id_pais, pais) VALUES (2, 'Venezuela');
INSERT INTO public.pais (id_pais, pais) VALUES (3, 'Peru');
INSERT INTO public.pais (id_pais, pais) VALUES (4, 'Ecuador');
INSERT INTO public.pais (id_pais, pais) VALUES (5, 'Chile');
INSERT INTO public.pais (id_pais, pais) VALUES (6, 'Argentina');
INSERT INTO public.pais (id_pais, pais) VALUES (7, 'Brasil');
INSERT INTO public.pais (id_pais, pais) VALUES (8, 'Uruguay');
INSERT INTO public.pais (id_pais, pais) VALUES (9, 'Paraguay');
